openapi: 3.0.0
info:
  description: Bitqueue API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Bitqueue API
  version: "1.0"
externalDocs:
  description: https://github.com/codelyrics/bitqueue-api/wiki/About-Bitqueue-(v0.1)
  url: https://github.com/codelyrics/bitqueue-api/wiki/About-Bitqueue-(v0.1)
servers:
- description: BitQueue API endpoints
  url: http://0.0.0.0:80/bitqueue/api
paths:
  /org:
    get:
      description: Return Organization Details.
      operationId: get_org
      parameters:
      - description: Organization name
        explode: true
        in: query
        name: orgname
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/org'
          description: OK
        "500":
          description: Error
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      description: Create Organization
      operationId: create_org
      parameters:
      - description: Organization name
        explode: true
        in: query
        name: orgname
        required: true
        schema:
          type: string
        style: form
      responses:
        "201":
          description: Created
        "404":
          description: Not Found
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /org/{orgid}:
    delete:
      description: Delete Organization
      operationId: delete_org
      parameters:
      - description: Organization ID
        explode: false
        in: path
        name: orgid
        required: true
        schema:
          default: 1
          format: int64
          maximum: 99999
          minimum: 1
          type: integer
        style: simple
      responses:
        "204":
          description: Organization is deleted.
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /org/{orgid}/tenant:
    get:
      description: Get tenants details
      operationId: get_tenant_list
      parameters:
      - description: Organization ID
        explode: false
        in: path
        name: orgid
        required: true
        schema:
          default: 1
          format: int64
          maximum: 99999
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/tenants'
          description: OK
        "500":
          description: Error
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      description: Create tenant
      operationId: create_tenant
      parameters:
      - description: Organization ID
        explode: false
        in: path
        name: orgid
        required: true
        schema:
          default: 1
          format: int64
          maximum: 99999
          minimum: 1
          type: integer
        style: simple
      - description: Tenant name
        explode: true
        in: query
        name: tenantname
        required: true
        schema:
          type: string
        style: form
      responses:
        "201":
          description: Created
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /org/{orgid}/tenant/{tenantid}:
    delete:
      description: delete tenant
      operationId: delete_tenant
      parameters:
      - description: Organization ID
        explode: false
        in: path
        name: orgid
        required: true
        schema:
          default: 1
          format: int64
          maximum: 99999
          minimum: 1
          type: integer
        style: simple
      - description: Tenant Id
        explode: false
        in: path
        name: tenantid
        required: true
        schema:
          default: 1
          format: int64
          maximum: 99999
          minimum: 1
          type: integer
        style: simple
      responses:
        "204":
          description: Tenant deleted
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      description: Get tenants details
      operationId: get_tenant_by_id
      parameters:
      - description: Organization ID
        explode: false
        in: path
        name: orgid
        required: true
        schema:
          default: 1
          format: int64
          maximum: 99999
          minimum: 1
          type: integer
        style: simple
      - description: Tenant Id
        explode: false
        in: path
        name: tenantid
        required: true
        schema:
          default: 1
          format: int64
          maximum: 99999
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/tenant'
          description: OK
        "500":
          description: Error
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  parameters:
    orgid:
      description: Organization ID
      explode: false
      in: path
      name: orgid
      required: true
      schema:
        default: 1
        format: int64
        maximum: 99999
        minimum: 1
        type: integer
      style: simple
    tenantid:
      description: Tenant Id
      explode: false
      in: path
      name: tenantid
      required: true
      schema:
        default: 1
        format: int64
        maximum: 99999
        minimum: 1
        type: integer
      style: simple
    orgname:
      description: Organization name
      explode: true
      in: query
      name: orgname
      required: true
      schema:
        type: string
      style: form
    tenantname:
      description: Tenant name
      explode: true
      in: query
      name: tenantname
      required: true
      schema:
        type: string
      style: form
  schemas:
    org:
      example:
        created: 30-12-2020 12:31:50
        name: Redhat
        updated: 30-12-2020 12:31:50
        uuid: f1f62f20-db3c-11ea-87d0-0242ac130003
        orgid: 1234
      properties:
        name:
          type: string
        orgid:
          type: integer
        created:
          type: string
        updated:
          type: string
        uuid:
          type: string
      type: object
    tenant:
      example:
        name: tenant
        orgid: 1234
        tenantid: 2342
        created: 30-12-2020 12:31:50
        updated: 30-12-2020 12:31:50
        uuid: f1f62f20-db3c-11ea-87d0-0242ac130003
      properties:
        name:
          type: string
        orgid:
          type: integer
        tenantid:
          type: integer
        created:
          type: string
        updated:
          type: string
        uuid:
          type: string
      type: object
    tenants:
      items:
        $ref: '#/components/schemas/tenant'
      type: array
