# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Tenant(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, orgid=None, tenantid=None, created=None, updated=None, uuid=None):  # noqa: E501
        """Tenant - a model defined in OpenAPI

        :param name: The name of this Tenant.  # noqa: E501
        :type name: str
        :param orgid: The orgid of this Tenant.  # noqa: E501
        :type orgid: int
        :param tenantid: The tenantid of this Tenant.  # noqa: E501
        :type tenantid: int
        :param created: The created of this Tenant.  # noqa: E501
        :type created: str
        :param updated: The updated of this Tenant.  # noqa: E501
        :type updated: str
        :param uuid: The uuid of this Tenant.  # noqa: E501
        :type uuid: str
        """
        self.openapi_types = {
            'name': str,
            'orgid': int,
            'tenantid': int,
            'created': str,
            'updated': str,
            'uuid': str
        }

        self.attribute_map = {
            'name': 'name',
            'orgid': 'orgid',
            'tenantid': 'tenantid',
            'created': 'created',
            'updated': 'updated',
            'uuid': 'uuid'
        }

        self._name = name
        self._orgid = orgid
        self._tenantid = tenantid
        self._created = created
        self._updated = updated
        self._uuid = uuid

    @classmethod
    def from_dict(cls, dikt) -> 'Tenant':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tenant of this Tenant.  # noqa: E501
        :rtype: Tenant
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this Tenant.


        :return: The name of this Tenant.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Tenant.


        :param name: The name of this Tenant.
        :type name: str
        """

        self._name = name

    @property
    def orgid(self):
        """Gets the orgid of this Tenant.


        :return: The orgid of this Tenant.
        :rtype: int
        """
        return self._orgid

    @orgid.setter
    def orgid(self, orgid):
        """Sets the orgid of this Tenant.


        :param orgid: The orgid of this Tenant.
        :type orgid: int
        """

        self._orgid = orgid

    @property
    def tenantid(self):
        """Gets the tenantid of this Tenant.


        :return: The tenantid of this Tenant.
        :rtype: int
        """
        return self._tenantid

    @tenantid.setter
    def tenantid(self, tenantid):
        """Sets the tenantid of this Tenant.


        :param tenantid: The tenantid of this Tenant.
        :type tenantid: int
        """

        self._tenantid = tenantid

    @property
    def created(self):
        """Gets the created of this Tenant.


        :return: The created of this Tenant.
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Tenant.


        :param created: The created of this Tenant.
        :type created: str
        """

        self._created = created

    @property
    def updated(self):
        """Gets the updated of this Tenant.


        :return: The updated of this Tenant.
        :rtype: str
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this Tenant.


        :param updated: The updated of this Tenant.
        :type updated: str
        """

        self._updated = updated

    @property
    def uuid(self):
        """Gets the uuid of this Tenant.


        :return: The uuid of this Tenant.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this Tenant.


        :param uuid: The uuid of this Tenant.
        :type uuid: str
        """

        self._uuid = uuid
